USER-SUPPLIED VALUES:
grafana:
  enabled: false
loki:
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 24h
prometheus:
  enabled: false
promtail:
  enabled: false
